### ISSUE TITLE
Доделать список чатов

### ISSUE THREAD

**Issue by NekrodNIK** [MoreliaTalk/morelia_client_flutter#2]
Доделать сами чаты и их список, а также добавить вариации списка чатов для разных платформ

**Comment by stepanskryabin** [comment]
Что значит "вариации" списка чатов?

**Comment by NekrodNIK** [comment]
Это значит, что компонент выдаëт возращает разные виджеты для разных платформ, к примеру, добавляя padding для мобилок, и убирая его для пк
